# Generated by Django 3.2.6 on 2022-03-20 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('qaapp', '0002_auto_20220317_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaapp',
            name='created',
        ),
        migrations.AddField(
            model_name='qaapp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qaapp',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='qaapp',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='qaapp',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='qaapp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
